version: '2'

services:
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    container_name: redis
  node:
    depends_on: 
      - redis
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/node:12'
    command: sh -c 'npm install && npm run build && npm start'
    links:
      - redis:redis
    ports:
      - 8080:8080
    volumes:
      - .:/app
    container_name: proxy

volumes:
  redis_data:
    driver: local
