version: '2'

services:
  redis:
    image: 'bitnami/redis:5.0'
    environment:
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
  # node:
  #   tty: true # Enables debugging capabilities when attached to this container.
  #   image: 'bitnami/node:12'
  #   command: sh -c 'npm start'
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - .:/app

volumes:
  redis_data:
    driver: local
